# Generated by Django 4.2.3 on 2023-07-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollos',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
