# Generated by Django 4.2.3 on 2023-07-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_rollos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollos',
            name='metros',
            field=models.CharField(max_length=10),
        ),
    ]
